### ISSUE TITLE
Variation of results of video streaming experiment

### ISSUE THREAD

**Issue by may3141** [SIGCOMM21-5G/artifact#15]
When I run the prediction experiments for 5G video streaming, the results in the plot vary by a small amount for each run of the experiment, even though the trace files are not changed. What may be the reason for this variation?

**Comment by ry4nzhu** [comment]
The prediction experiment uses prediction traces with 1 second granularity. The result might vary a little bit depending on the choice of prediction bandwidth and timestamp when choosing the prediction bandwidth in that trace (i.e. the choice of predicted bandwidth is related to the time when a chunk finished downloading). So that is normal to have small variation.
